# Generated by Django 3.2.5 on 2021-08-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('startBid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=1)),
            ],
        ),
    ]
