# Generated by Django 3.2.5 on 2021-08-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startBid',
            new_name='bid',
        ),
    ]
