# Generated by Django 3.2.5 on 2021-08-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name_plural': 'bids'},
        ),
    ]
