# Generated by Django 3.2.5 on 2021-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listing_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'watchlist',
            },
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='listingid',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listingid',
            new_name='listing_id',
        ),
    ]
