# Generated by Django 3.2.5 on 2021-08-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210804_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listingId',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listingId',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='startBid',
            new_name='start_bid',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingId',
            new_name='listing_id',
        ),
    ]
