# Generated by Django 3.2.5 on 2021-08-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_watchlist_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
