# Generated by Django 3.2.5 on 2021-08-09 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
