# Generated by Django 3.2.5 on 2021-08-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210809_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
