# Generated by Django 3.2.5 on 2021-08-12 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_bids_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('winner', models.CharField(blank=True, max_length=64, null=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bids')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.listing')),
            ],
            options={
                'verbose_name_plural': 'winners',
            },
        ),
    ]
