# Generated by Django 3.2.5 on 2021-09-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20210818_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-date',), 'verbose_name_plural': 'comments'},
        ),
    ]
