# Generated by Django 3.2.5 on 2021-09-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
